### ISSUE TITLE
ssh-keygen error

### ISSUE THREAD

**Issue by hirurg-lybitel** [stasgm/docker-jenkins#1]
Hi there.

I tried to generate ssh by your instruction (step 2), but I got an error:
```shell
D:\Git\docker-jenkins>ssh-keygen -f ~/.ssh/jenkins_agent_key
Generating public/private rsa key pair.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Saving key "~/.ssh/jenkins_agent_key" failed: No such file or directory
```

I guess the repo needs  `.ssh` folder.
Or maybe is there some specify option for command `ssh-keygen`?

Thank you for help

**Comment by stasgm** [comment]
Hi @hirurg-lybitel 
I'm sorry. I should have mentioned that this instruction is for Linux OS.
You can use [this article](https://www.howtogeek.com/762863/how-to-generate-ssh-keys-in-windows-10-and-windows-11/)  to generate ssh on Windows
